/**
 * Demo hospital dataset with realistic coordinates for major Indian cities.
 * Each entry includes GPS coords, specialties, ratings, emergency status, etc.
 */

export const CITIES = [
  { id: "kalaburagi", name: "Kalaburagi", lat: 17.3297, lng: 76.8343 },
  { id: "bengaluru",  name: "Bengaluru",  lat: 12.9716, lng: 77.5946 },
  { id: "hyderabad",  name: "Hyderabad",  lat: 17.3850, lng: 78.4867 },
  { id: "mumbai",     name: "Mumbai",     lat: 19.0760, lng: 72.8777 },
  { id: "delhi",      name: "Delhi",      lat: 28.6139, lng: 77.2090 },
  { id: "chennai",    name: "Chennai",    lat: 13.0827, lng: 80.2707 },
  { id: "pune",       name: "Pune",       lat: 18.5204, lng: 73.8567 },
];

export const HOSPITALS = [
  // ── Kalaburagi ──────────────────────────────────────────────────────────────
  {
    id: "klb-1", city: "kalaburagi",
    name: "Basaveshwar Teaching & General Hospital",
    lat: 17.3310, lng: 76.8200,
    rating: 4.2, distance: 1.2,
    emergency: true, open: true,
    specialties: ["General Medicine", "Surgery", "Orthopaedics"],
    phone: "+91-8472-263000",
    address: "Sedam Road, Kalaburagi",
    aiRecommended: true,
    beds: 850,
  },
  {
    id: "klb-2", city: "kalaburagi",
    name: "ESIC Model Hospital Kalaburagi",
    lat: 17.3350, lng: 76.8450,
    rating: 3.9, distance: 2.1,
    emergency: true, open: true,
    specialties: ["Cardiology", "Neurology", "Paediatrics"],
    phone: "+91-8472-255000",
    address: "Industrial Area, Kalaburagi",
    aiRecommended: false,
    beds: 300,
  },
  {
    id: "klb-3", city: "kalaburagi",
    name: "Gulbarga Institute of Medical Sciences",
    lat: 17.3270, lng: 76.8380,
    rating: 4.5, distance: 0.8,
    emergency: true, open: true,
    specialties: ["Oncology", "Nephrology", "Gynaecology"],
    phone: "+91-8472-278000",
    address: "GIMS Campus, Kalaburagi",
    aiRecommended: true,
    beds: 1200,
  },
  {
    id: "klb-4", city: "kalaburagi",
    name: "Navodaya Medical College Hospital",
    lat: 17.3180, lng: 76.8290,
    rating: 4.0, distance: 3.4,
    emergency: false, open: true,
    specialties: ["Dermatology", "ENT", "Ophthalmology"],
    phone: "+91-8472-261000",
    address: "Mantralayam Road, Kalaburagi",
    aiRecommended: false,
    beds: 500,
  },
  {
    id: "klb-5", city: "kalaburagi",
    name: "Shri Shivayogi Mrityunjaya Hospital",
    lat: 17.3400, lng: 76.8500,
    rating: 3.7, distance: 4.0,
    emergency: true, open: false,
    specialties: ["General Surgery", "Urology"],
    phone: "+91-8472-244000",
    address: "Super Market Area, Kalaburagi",
    aiRecommended: false,
    beds: 200,
  },

  // ── Bengaluru ────────────────────────────────────────────────────────────────
  {
    id: "blr-1", city: "bengaluru",
    name: "Manipal Hospital (Old Airport Road)",
    lat: 12.9591, lng: 77.6480,
    rating: 4.7, distance: 2.3,
    emergency: true, open: true,
    specialties: ["Cardiology", "Neurosciences", "Oncology", "Transplant"],
    phone: "+91-80-25024444",
    address: "98, HAL Airport Road, Bengaluru",
    aiRecommended: true,
    beds: 600,
  },
  {
    id: "blr-2", city: "bengaluru",
    name: "Fortis Hospital Bannerghatta",
    lat: 12.8900, lng: 77.5970,
    rating: 4.5, distance: 5.1,
    emergency: true, open: true,
    specialties: ["Orthopaedics", "Cardiac Surgery", "Robotics"],
    phone: "+91-80-66214444",
    address: "154/9, Bannerghatta Road, Bengaluru",
    aiRecommended: false,
    beds: 400,
  },
  {
    id: "blr-3", city: "bengaluru",
    name: "Narayana Health City",
    lat: 12.8960, lng: 77.6040,
    rating: 4.6, distance: 4.8,
    emergency: true, open: true,
    specialties: ["Cardiac", "Paediatric Surgery", "Bone Marrow Transplant"],
    phone: "+91-80-71222222",
    address: "258/A, Bommasandra, Bengaluru",
    aiRecommended: true,
    beds: 1400,
  },
  {
    id: "blr-4", city: "bengaluru",
    name: "St. John's Medical College Hospital",
    lat: 12.9350, lng: 77.6200,
    rating: 4.4, distance: 3.2,
    emergency: true, open: true,
    specialties: ["General Medicine", "Psychiatry", "Nephrology"],
    phone: "+91-80-22065000",
    address: "Sarjapur Road, Bengaluru",
    aiRecommended: false,
    beds: 1300,
  },

  // ── Hyderabad ────────────────────────────────────────────────────────────────
  {
    id: "hyd-1", city: "hyderabad",
    name: "Apollo Hospitals Jubilee Hills",
    lat: 17.4239, lng: 78.4072,
    rating: 4.8, distance: 1.9,
    emergency: true, open: true,
    specialties: ["Cardiology", "Oncology", "Neurology", "Transplant"],
    phone: "+91-40-23607777",
    address: "Jubilee Hills, Hyderabad",
    aiRecommended: true,
    beds: 700,
  },
  {
    id: "hyd-2", city: "hyderabad",
    name: "KIMS Hospital Secunderabad",
    lat: 17.4399, lng: 78.4983,
    rating: 4.3, distance: 3.5,
    emergency: true, open: true,
    specialties: ["Orthopaedics", "Spine Surgery", "Urology"],
    phone: "+91-40-44885000",
    address: "1-8-31/1, Minister Road, Secunderabad",
    aiRecommended: false,
    beds: 1000,
  },
  {
    id: "hyd-3", city: "hyderabad",
    name: "Yashoda Hospital Somajiguda",
    lat: 17.4239, lng: 78.4567,
    rating: 4.4, distance: 2.7,
    emergency: true, open: true,
    specialties: ["Gastroenterology", "Liver Transplant", "Bariatrics"],
    phone: "+91-40-45674567",
    address: "Raj Bhavan Road, Somajiguda, Hyderabad",
    aiRecommended: true,
    beds: 550,
  },

  // ── Mumbai ───────────────────────────────────────────────────────────────────
  {
    id: "mum-1", city: "mumbai",
    name: "Kokilaben Dhirubhai Ambani Hospital",
    lat: 19.1136, lng: 72.8697,
    rating: 4.8, distance: 2.1,
    emergency: true, open: true,
    specialties: ["Robotic Surgery", "Cardiac", "Neurosciences", "Cancer"],
    phone: "+91-22-30999999",
    address: "Rao Saheb Achutrao Patwardhan Marg, Mumbai",
    aiRecommended: true,
    beds: 750,
  },
  {
    id: "mum-2", city: "mumbai",
    name: "Lilavati Hospital Bandra",
    lat: 19.0544, lng: 72.8258,
    rating: 4.6, distance: 3.8,
    emergency: true, open: true,
    specialties: ["Cardiology", "Orthopaedics", "Gynaecology"],
    phone: "+91-22-26751000",
    address: "A-791, Bandra Reclamation, Mumbai",
    aiRecommended: false,
    beds: 323,
  },
  {
    id: "mum-3", city: "mumbai",
    name: "Tata Memorial Hospital",
    lat: 18.9988, lng: 72.8126,
    rating: 4.9, distance: 6.2,
    emergency: true, open: true,
    specialties: ["Oncology", "Haematology", "Radiation Therapy"],
    phone: "+91-22-24177000",
    address: "Dr. E Borges Road, Parel, Mumbai",
    aiRecommended: true,
    beds: 629,
  },

  // ── Delhi ────────────────────────────────────────────────────────────────────
  {
    id: "del-1", city: "delhi",
    name: "AIIMS New Delhi",
    lat: 28.5672, lng: 77.2100,
    rating: 4.9, distance: 3.1,
    emergency: true, open: true,
    specialties: ["All Specialties", "Research", "Trauma"],
    phone: "+91-11-26588500",
    address: "Sri Aurobindo Marg, Ansari Nagar, New Delhi",
    aiRecommended: true,
    beds: 2478,
  },
  {
    id: "del-2", city: "delhi",
    name: "Max Super Speciality Hospital Saket",
    lat: 28.5245, lng: 77.2066,
    rating: 4.6, distance: 4.5,
    emergency: true, open: true,
    specialties: ["Cardiac Surgery", "Neurology", "Oncology"],
    phone: "+91-11-26515050",
    address: "2, Press Enclave Road, Saket, New Delhi",
    aiRecommended: false,
    beds: 500,
  },
  {
    id: "del-3", city: "delhi",
    name: "Fortis Escorts Heart Institute",
    lat: 28.5621, lng: 77.2841,
    rating: 4.7, distance: 5.9,
    emergency: true, open: true,
    specialties: ["Cardiology", "Cardiac Surgery", "Electrophysiology"],
    phone: "+91-11-47135000",
    address: "Okhla Road, New Delhi",
    aiRecommended: true,
    beds: 310,
  },

  // ── Chennai ──────────────────────────────────────────────────────────────────
  {
    id: "che-1", city: "chennai",
    name: "Apollo Hospitals Greams Road",
    lat: 13.0569, lng: 80.2425,
    rating: 4.8, distance: 2.4,
    emergency: true, open: true,
    specialties: ["Cardiology", "Transplant", "Oncology", "Neurology"],
    phone: "+91-44-28290200",
    address: "21, Greams Lane, Chennai",
    aiRecommended: true,
    beds: 560,
  },
  {
    id: "che-2", city: "chennai",
    name: "MIOT International Hospital",
    lat: 13.0418, lng: 80.1760,
    rating: 4.5, distance: 5.3,
    emergency: true, open: true,
    specialties: ["Orthopaedics", "Joint Replacement", "Sports Medicine"],
    phone: "+91-44-42002288",
    address: "4/112, Mount Poonamallee Road, Chennai",
    aiRecommended: false,
    beds: 1000,
  },

  // ── Pune ─────────────────────────────────────────────────────────────────────
  {
    id: "pun-1", city: "pune",
    name: "Ruby Hall Clinic",
    lat: 18.5314, lng: 73.8446,
    rating: 4.6, distance: 1.7,
    emergency: true, open: true,
    specialties: ["Cardiology", "Neurology", "Oncology", "Transplant"],
    phone: "+91-20-66455000",
    address: "40, Sassoon Road, Pune",
    aiRecommended: true,
    beds: 450,
  },
  {
    id: "pun-2", city: "pune",
    name: "Jehangir Hospital",
    lat: 18.5236, lng: 73.8731,
    rating: 4.4, distance: 2.9,
    emergency: true, open: true,
    specialties: ["General Surgery", "Gynaecology", "Paediatrics"],
    phone: "+91-20-66810000",
    address: "32, Sassoon Road, Pune",
    aiRecommended: false,
    beds: 350,
  },
  {
    id: "pun-3", city: "pune",
    name: "Deenanath Mangeshkar Hospital",
    lat: 18.5089, lng: 73.8259,
    rating: 4.5, distance: 3.6,
    emergency: true, open: true,
    specialties: ["Cardiac", "Neurosciences", "Renal", "Oncology"],
    phone: "+91-20-49150000",
    address: "Erandwane, Pune",
    aiRecommended: true,
    beds: 600,
  },
];

/** Return hospitals for a given city id, sorted by distance */
export function getHospitalsByCity(cityId) {
  return HOSPITALS
    .filter((h) => h.city === cityId)
    .sort((a, b) => a.distance - b.distance);
}

/** Return city object by id */
export function getCityById(cityId) {
  return CITIES.find((c) => c.id === cityId) ?? CITIES[0];
}
