/**
 * Medical Awareness & Precaution Modules — static educational dataset.
 * ⚠️  For awareness only. Not a prescription system.
 */

export const CATEGORIES = [
  { id: "all",        label: "All",                  emoji: "💊", color: "sky" },
  { id: "fever",      label: "Fever & Pain Relief",  emoji: "🌡️", color: "orange" },
  { id: "cold",       label: "Cold & Allergy",       emoji: "🤧", color: "blue" },
  { id: "digestion",  label: "Digestion & Acidity",  emoji: "🫁", color: "green" },
  { id: "vitamins",   label: "Vitamins & Supplements",emoji: "✨", color: "yellow" },
  { id: "skin",       label: "Skin & First Aid",     emoji: "🩹", color: "pink" },
];

export const MEDICINES = [
  // ── Fever & Pain Relief ──────────────────────────────────────────────────
  {
    id: "paracetamol",
    name: "Paracetamol",
    brand: "Crocin / Dolo / Tylenol",
    category: "fever",
    emoji: "🌡️",
    gradient: "from-orange-400 to-amber-400",
    bgLight: "bg-orange-50",
    borderColor: "border-orange-200",
    tagColor: "bg-orange-100 text-orange-700",
    uses: [
      "Reduces fever (antipyretic)",
      "Relieves mild to moderate pain",
      "Headache and body ache relief",
      "Post-vaccination fever management",
    ],
    precautions: [
      "Do not exceed recommended frequency",
      "Avoid alcohol while taking this medicine",
      "Not suitable for people with liver conditions",
      "Do not combine with other paracetamol-containing products",
    ],
    sideEffects: ["Nausea (rare)", "Skin rash (rare)", "Liver stress if overused"],
    ageGuidance: {
      children: "Use under medical supervision — weight-based guidance needed",
      adults: "Follow package instructions carefully",
      elderly: "Consult doctor — reduced frequency may be advised",
    },
    emergencyNote: null,
    aiTip: "Paracetamol is one of the safest OTC medicines when used correctly. Always check the label.",
  },
  {
    id: "ibuprofen",
    name: "Ibuprofen",
    brand: "Brufen / Advil / Nurofen",
    category: "fever",
    emoji: "💊",
    gradient: "from-red-400 to-orange-400",
    bgLight: "bg-red-50",
    borderColor: "border-red-200",
    tagColor: "bg-red-100 text-red-700",
    uses: [
      "Anti-inflammatory pain relief",
      "Fever reduction",
      "Muscle and joint pain",
      "Menstrual cramp relief",
    ],
    precautions: [
      "Take with food to protect stomach lining",
      "Avoid if you have kidney or stomach ulcer history",
      "Not recommended during pregnancy (especially 3rd trimester)",
      "Avoid with blood thinners without doctor advice",
    ],
    sideEffects: ["Stomach upset", "Heartburn", "Dizziness", "Increased blood pressure (long-term)"],
    ageGuidance: {
      children: "Not recommended under 6 months — consult paediatrician",
      adults: "Follow package instructions; take with food",
      elderly: "Use with caution — consult doctor due to kidney/stomach risks",
    },
    emergencyNote: null,
    aiTip: "Ibuprofen is an NSAID — it reduces inflammation. Always take with food.",
  },
  {
    id: "aspirin",
    name: "Aspirin",
    brand: "Disprin / Ecosprin / Bayer Aspirin",
    category: "fever",
    emoji: "❤️",
    gradient: "from-rose-400 to-red-400",
    bgLight: "bg-rose-50",
    borderColor: "border-rose-200",
    tagColor: "bg-rose-100 text-rose-700",
    uses: [
      "Pain and fever relief",
      "Anti-inflammatory",
      "Low-dose: heart health support (under doctor guidance)",
      "Blood clot prevention (prescribed use)",
    ],
    precautions: [
      "Never give to children under 16 — risk of Reye's syndrome",
      "Avoid if you have bleeding disorders",
      "Do not take on empty stomach",
      "Consult doctor before use if on blood thinners",
    ],
    sideEffects: ["Stomach bleeding (with overuse)", "Tinnitus (ringing in ears)", "Nausea"],
    ageGuidance: {
      children: "⚠️ NOT recommended for children under 16",
      adults: "Follow package instructions; take with food",
      elderly: "Consult doctor — increased bleeding risk",
    },
    emergencyNote: "⚠️ Never give Aspirin to children — risk of serious Reye's syndrome",
    aiTip: "Aspirin has important restrictions. Always read the label and consult a doctor for regular use.",
  },

  // ── Cold & Allergy ───────────────────────────────────────────────────────
  {
    id: "cetirizine",
    name: "Cetirizine",
    brand: "Zyrtec / Cetzine / Alerid",
    category: "cold",
    emoji: "🤧",
    gradient: "from-blue-400 to-sky-400",
    bgLight: "bg-blue-50",
    borderColor: "border-blue-200",
    tagColor: "bg-blue-100 text-blue-700",
    uses: [
      "Allergic rhinitis (hay fever)",
      "Skin allergies and hives (urticaria)",
      "Itchy, watery eyes",
      "Sneezing and runny nose relief",
    ],
    precautions: [
      "May cause drowsiness — avoid driving",
      "Avoid alcohol",
      "Use with caution in kidney disease",
      "Inform doctor if pregnant or breastfeeding",
    ],
    sideEffects: ["Drowsiness", "Dry mouth", "Headache", "Fatigue"],
    ageGuidance: {
      children: "Paediatric formulations available — consult doctor for correct form",
      adults: "Usually once daily; follow package instructions",
      elderly: "May cause more drowsiness — consult doctor",
    },
    emergencyNote: null,
    aiTip: "Cetirizine is a second-generation antihistamine — less drowsy than older antihistamines.",
  },

  // ── Digestion & Acidity ──────────────────────────────────────────────────
  {
    id: "pantoprazole",
    name: "Pantoprazole",
    brand: "Pantocid / Pan-D / Protonix",
    category: "digestion",
    emoji: "🫁",
    gradient: "from-green-400 to-teal-400",
    bgLight: "bg-green-50",
    borderColor: "border-green-200",
    tagColor: "bg-green-100 text-green-700",
    uses: [
      "Acid reflux (GERD) management",
      "Stomach ulcer awareness",
      "Reduces excess stomach acid",
      "Heartburn relief",
    ],
    precautions: [
      "Usually taken before meals",
      "Not for immediate heartburn relief",
      "Long-term use should be under doctor supervision",
      "May affect magnesium levels with prolonged use",
    ],
    sideEffects: ["Headache", "Diarrhoea", "Nausea", "Stomach pain (rare)"],
    ageGuidance: {
      children: "Use only under paediatric doctor guidance",
      adults: "Follow doctor's prescription; typically before breakfast",
      elderly: "Consult doctor — may interact with other medications",
    },
    emergencyNote: null,
    aiTip: "Pantoprazole is a PPI (Proton Pump Inhibitor). It reduces acid production rather than neutralising it.",
  },
  {
    id: "omeprazole",
    name: "Omeprazole",
    brand: "Omez / Prilosec / Losec",
    category: "digestion",
    emoji: "💚",
    gradient: "from-emerald-400 to-green-400",
    bgLight: "bg-emerald-50",
    borderColor: "border-emerald-200",
    tagColor: "bg-emerald-100 text-emerald-700",
    uses: [
      "Gastric acid reduction",
      "GERD and acid reflux",
      "Stomach and duodenal ulcers",
      "Zollinger-Ellison syndrome (prescribed)",
    ],
    precautions: [
      "Take 30–60 minutes before eating",
      "Do not crush or chew capsules",
      "Avoid long-term use without medical supervision",
      "May reduce absorption of certain vitamins (B12, magnesium)",
    ],
    sideEffects: ["Headache", "Constipation or diarrhoea", "Flatulence", "Nausea"],
    ageGuidance: {
      children: "Consult paediatrician — not for general OTC use in children",
      adults: "Follow prescription; typically once daily before meals",
      elderly: "Consult doctor — monitor for bone density with long-term use",
    },
    emergencyNote: null,
    aiTip: "Omeprazole and Pantoprazole are both PPIs — similar mechanism, slightly different profiles.",
  },
  {
    id: "ors",
    name: "ORS (Oral Rehydration Salts)",
    brand: "Electral / Pedialyte / WHO-ORS",
    category: "digestion",
    emoji: "💧",
    gradient: "from-cyan-400 to-blue-400",
    bgLight: "bg-cyan-50",
    borderColor: "border-cyan-200",
    tagColor: "bg-cyan-100 text-cyan-700",
    uses: [
      "Rehydration after diarrhoea or vomiting",
      "Dehydration from fever or heat",
      "Electrolyte replenishment",
      "Post-exercise recovery",
    ],
    precautions: [
      "Mix with clean, safe drinking water only",
      "Use freshly prepared solution within 24 hours",
      "Do not add extra sugar or salt",
      "Seek medical help if dehydration is severe",
    ],
    sideEffects: ["Generally very safe", "Nausea if taken too quickly", "Hypernatraemia if overused (rare)"],
    ageGuidance: {
      children: "Safe and recommended — follow WHO guidelines for mixing",
      adults: "Drink slowly in small sips; follow package instructions",
      elderly: "Consult doctor if on heart or kidney medication",
    },
    emergencyNote: "💧 For severe dehydration (sunken eyes, no urination, confusion) — seek emergency care immediately",
    aiTip: "ORS is a life-saving solution. The WHO formula is the gold standard for rehydration.",
  },

  // ── Vitamins & Supplements ───────────────────────────────────────────────
  {
    id: "vitamin-c",
    name: "Vitamin C",
    brand: "Limcee / Celin / Ester-C",
    category: "vitamins",
    emoji: "🍊",
    gradient: "from-yellow-400 to-orange-400",
    bgLight: "bg-yellow-50",
    borderColor: "border-yellow-200",
    tagColor: "bg-yellow-100 text-yellow-700",
    uses: [
      "Immune system support",
      "Antioxidant protection",
      "Collagen synthesis for skin health",
      "Iron absorption enhancement",
    ],
    precautions: [
      "High doses may cause kidney stones in susceptible individuals",
      "Excess vitamin C is excreted but very high doses cause GI upset",
      "Inform doctor if taking blood thinners",
      "Chewable tablets may affect tooth enamel — rinse mouth after",
    ],
    sideEffects: ["Stomach upset (high doses)", "Diarrhoea (high doses)", "Kidney stones (very high doses, rare)"],
    ageGuidance: {
      children: "Dietary sources preferred; supplements under paediatric guidance",
      adults: "Follow package instructions; dietary sources are ideal",
      elderly: "Generally safe; consult doctor for supplement doses",
    },
    emergencyNote: null,
    aiTip: "Vitamin C from food (citrus, amla, guava) is always better than supplements.",
  },
  {
    id: "zinc",
    name: "Zinc",
    brand: "Zincovit / Zinconia / Nature's Bounty Zinc",
    category: "vitamins",
    emoji: "⚡",
    gradient: "from-violet-400 to-purple-400",
    bgLight: "bg-violet-50",
    borderColor: "border-violet-200",
    tagColor: "bg-violet-100 text-violet-700",
    uses: [
      "Immune function support",
      "Wound healing",
      "Taste and smell function",
      "Diarrhoea management in children (WHO protocol)",
    ],
    precautions: [
      "Do not take on empty stomach — causes nausea",
      "Avoid high doses — can interfere with copper absorption",
      "Space apart from iron or calcium supplements",
      "Consult doctor before use during pregnancy",
    ],
    sideEffects: ["Nausea", "Stomach cramps", "Metallic taste", "Copper deficiency (long-term high doses)"],
    ageGuidance: {
      children: "Used in diarrhoea management — follow WHO/doctor guidance",
      adults: "Take with food; follow package instructions",
      elderly: "Consult doctor — may interact with medications",
    },
    emergencyNote: null,
    aiTip: "Zinc is essential for immunity. Dietary sources include nuts, seeds, legumes, and meat.",
  },

  // ── Skin & First Aid ─────────────────────────────────────────────────────
  {
    id: "betadine",
    name: "Betadine (Povidone-Iodine)",
    brand: "Betadine / Wokadine",
    category: "skin",
    emoji: "🩹",
    gradient: "from-amber-500 to-yellow-500",
    bgLight: "bg-amber-50",
    borderColor: "border-amber-200",
    tagColor: "bg-amber-100 text-amber-700",
    uses: [
      "Wound cleaning and disinfection",
      "Minor cuts and abrasions",
      "Pre-surgical skin preparation",
      "Mouth ulcer rinse (diluted)",
    ],
    precautions: [
      "Do not use on deep wounds without medical advice",
      "Avoid contact with eyes",
      "Not for prolonged use on large areas",
      "Inform doctor if thyroid condition exists",
      "Do not use on newborns without medical guidance",
    ],
    sideEffects: ["Skin irritation", "Staining of skin/clothes", "Allergic reaction (rare)", "Thyroid interference (large area use)"],
    ageGuidance: {
      children: "Use with caution — consult doctor for infants",
      adults: "Apply to clean wound; follow package instructions",
      elderly: "Generally safe for topical use; consult doctor for large wounds",
    },
    emergencyNote: null,
    aiTip: "Betadine is a broad-spectrum antiseptic. Always clean the wound with water first.",
  },
  {
    id: "calamine",
    name: "Calamine Lotion",
    brand: "Lacto Calamine / Calamine BP",
    category: "skin",
    emoji: "🌸",
    gradient: "from-pink-400 to-rose-400",
    bgLight: "bg-pink-50",
    borderColor: "border-pink-200",
    tagColor: "bg-pink-100 text-pink-700",
    uses: [
      "Itching relief from insect bites",
      "Mild sunburn soothing",
      "Chickenpox itch relief",
      "Skin rash and irritation",
    ],
    precautions: [
      "For external use only",
      "Avoid contact with eyes",
      "Do not apply to broken or infected skin",
      "Shake well before use",
    ],
    sideEffects: ["Skin dryness (with frequent use)", "Mild irritation (rare)"],
    ageGuidance: {
      children: "Generally safe for topical use; avoid eye area",
      adults: "Apply as needed; follow package instructions",
      elderly: "Safe for topical use; monitor for skin dryness",
    },
    emergencyNote: null,
    aiTip: "Calamine lotion has a cooling, soothing effect. It's one of the safest topical preparations.",
  },
];

export const EMERGENCY_CARDS = [
  {
    id: "fever-emergency",
    title: "High Fever",
    emoji: "🌡️",
    gradient: "from-red-400 to-orange-400",
    bgLight: "bg-red-50",
    borderColor: "border-red-200",
    severity: "High",
    signs: ["Temperature above 103°F / 39.4°C", "Febrile seizures", "Confusion or disorientation", "Stiff neck with fever"],
    firstAid: [
      "Keep the person cool — remove excess clothing",
      "Apply cool (not cold) damp cloth to forehead",
      "Ensure adequate hydration",
      "Seek medical attention if fever persists over 3 days",
    ],
    warning: "Seek emergency care immediately if fever is above 104°F or accompanied by seizures",
  },
  {
    id: "dehydration",
    title: "Dehydration",
    emoji: "💧",
    gradient: "from-blue-400 to-cyan-400",
    bgLight: "bg-blue-50",
    borderColor: "border-blue-200",
    severity: "Medium",
    signs: ["Dry mouth and extreme thirst", "Dark yellow urine or no urination", "Dizziness and weakness", "Sunken eyes (severe)"],
    firstAid: [
      "Give ORS (Oral Rehydration Salts) solution",
      "Sip fluids slowly — do not gulp",
      "Avoid sugary drinks and caffeine",
      "Rest in a cool environment",
    ],
    warning: "Severe dehydration (confusion, no urination for 8+ hours) requires emergency medical care",
  },
  {
    id: "burns",
    title: "Minor Burns",
    emoji: "🔥",
    gradient: "from-orange-400 to-red-400",
    bgLight: "bg-orange-50",
    borderColor: "border-orange-200",
    severity: "Medium",
    signs: ["Redness and pain", "Small blisters", "Swelling around burn area"],
    firstAid: [
      "Cool the burn under running cool water for 10–20 minutes",
      "Do NOT use ice, butter, or toothpaste",
      "Cover loosely with a clean non-fluffy bandage",
      "Do not burst blisters",
    ],
    warning: "Seek emergency care for burns larger than 3 inches, burns on face/hands/genitals, or chemical burns",
  },
  {
    id: "allergic-reaction",
    title: "Allergic Reaction",
    emoji: "⚠️",
    gradient: "from-yellow-400 to-amber-400",
    bgLight: "bg-yellow-50",
    borderColor: "border-yellow-200",
    severity: "High",
    signs: ["Hives or skin rash", "Swelling of face, lips, or throat", "Difficulty breathing", "Rapid heartbeat"],
    firstAid: [
      "Remove or avoid the allergen if known",
      "For mild reactions: antihistamine may help",
      "Keep the person calm and seated upright",
      "Call emergency services for severe reactions",
    ],
    warning: "⚠️ Anaphylaxis (throat swelling, breathing difficulty) is life-threatening — call 112 immediately",
  },
  {
    id: "minor-injury",
    title: "Minor Cuts & Injuries",
    emoji: "🩹",
    gradient: "from-teal-400 to-green-400",
    bgLight: "bg-teal-50",
    borderColor: "border-teal-200",
    severity: "Low",
    signs: ["Small cuts or abrasions", "Minor bruising", "Superficial scrapes"],
    firstAid: [
      "Clean the wound with clean running water",
      "Apply gentle pressure with a clean cloth to stop bleeding",
      "Apply antiseptic (e.g., Betadine) after cleaning",
      "Cover with a sterile bandage",
    ],
    warning: "Seek medical care for deep wounds, wounds that won't stop bleeding, or animal bites",
  },
];

export function getMedicinesByCategory(categoryId) {
  if (categoryId === "all") return MEDICINES;
  return MEDICINES.filter((m) => m.category === categoryId);
}

export function searchMedicines(query) {
  const q = query.toLowerCase().trim();
  if (!q) return MEDICINES;
  return MEDICINES.filter(
    (m) =>
      m.name.toLowerCase().includes(q) ||
      m.brand.toLowerCase().includes(q) ||
      m.uses.some((u) => u.toLowerCase().includes(q)) ||
      m.category.toLowerCase().includes(q)
  );
}
